name: "StreamTracker"
main: net.twasiplugin.dependency.streamtracker.StreamTrackerPlugin
author: Twasi Team
description: Track stream data of all users
version: 1.0
hidden: true
autoInstall: true
messageHandler: true

api: |
  type StreamTracker {
    lastStream: Stream,
    streamsByRange(start: String, end: String): [Stream],
    lastStreamWithOffset(offset: Int): Stream,
    streamById(streamId: String): Stream,
    allStreamData: [StreamTrackEntity]
  }

  type Stream {
    streamId: String,
    language: String,
    startedAt: String,
    streamType: String,
    communityIds: [String],
    tagIds: [String],
    data: [StreamTrackEntity],
    topChatters: [StreamTrackChatter]
  }

  type StreamTrackEntity {
    gameId: String,
    game: String,
    title: String,
    viewerCount: Int,
    chatMessages: Int,
    chatCommands: Int,
    timestamp: String
  }

  type StreamTrackChatter {
    twitchId: String,
    displayName: String,
    messages: Int,
    commands: Int
  }