name: "StreamTracker"
main: net.twasiplugin.dependency.streamtracker.StreamTrackerDependency
author: Twasi Team
description: Track stream data of all users
version: 1.0

dependency: true

commands:

api: |
  type StreamTracker {
    lastStream: Stream,
    streamsByRange(start: String, end: String): [Stream],
    lastStreamWithOffset(offset: Int): Stream,
    allStreamData: [StreamTrackEntity]
  }

  type Stream {
    streamId: String,
    language: String,
    startedAt: String,
    streamType: String,
    communityIds: [String],
    tagIds: [String],
    data: [StreamTrackEntity]
  }

  type StreamTrackEntity {
    gameId: String,
    game: String,
    title: String,
    viewerCount: Int,
    timestamp: String
  }