package net.twasiplugin.dependency.database;

import net.twasi.core.database.lib.Repository;

public class StreamRepository extends Repository<StreamEntity> {

    /**
     * @param streamId String ID of the stream generated by Twitch
     * @return StreamEntity|null
     */
    public StreamEntity getStreamEntityByStreamId(String streamId) {
        try {
            return store.createQuery(StreamEntity.class).field("streamId").equal(streamId).asList().get(0);
        } catch (Exception e) {
            return null;
        }
    }

}
